apiVersion: v1
kind: Service
metadata:
  name: bootdemo
  labels:
    name: bootdemo
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: bootdemo
#  type: LoadBalancer
